travis:
  secure:
    BINSTAR_TOKEN: mz7dMnhxOstiaFomgwvGdKkHnyULjgKAV0m4v+vq5TaRZPI/ec/wdr9RyTR9ZOu6LU7TSTrtrUMUwnRGiRz0KcEz01c9iL3PbZVzG5lHvt2mGo/3p2/nYiAIvkenukC4kYf4slRvkhvaKdv8ziDOO47JBU5mlIwFzhBJ60RTDRfQtIKSZxLQDlDjRzeA4KPWC7es/7kRK7a8r701iySqePPJxeohXVKaDILQ5/OYxvhHVAw/yVPQkMj2nWFCgEn3btTpJMcbR63mwlPLeGC1VnW+mDUvwI4PonRpbGnBgegOhd559Tg88PM4ogsjnE9M5dbAep5e7XaaS7E1lLomaQOhecPVFZGrUQyH71X0kq7NA5MitavMrD9w0sgqRgqGGsoRbxjN2hO16nHrxX8Y+kpo5aBSiy1Xb3N/uYvf611GzmBzSvFoA30N8mLpuK+Bv+UmflF9drpI0/Y5qkZJ/xvwYP1abT3DbceyJCLsNCxZoEg8fNYpb2v50eSU41Gv2YprKmmwBKGGCFI+YJ0n4INf30w/2ej8ub/5V0SWwFiJudU4BOjt/MB1ZB6jro7Oipw2FGRo1Pv6LUOB74o7BqwbKJ+RWYkAjQ9KW5vG+bh68IC5w297O44FW4VP2jOblyqW359ahLQnHo+X8X8xeEECfP1Eu27171gYeotWQHc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
