travis:
  secure:
    BINSTAR_TOKEN: QpsqaZ5YbvZEbnwYDrFbZn7BgnVYsfFPBTDvh6/R1T+k+/j6RyGuCUvGPyT9juhSNP+Z9rUdUFMzjSicydyFMi769dItgNVq2svWEueP/TwYwWl1cWQtJoowzFlkOv0HeJEiGOpMAeKxvLoFDQL6oGy+pWLghV0vKks9zdZuSPFU6XMPYNMAnqUywEND+ZSKwFdVCIyohFGUrbjaiGQoCpES0OTFKngbxG0mfypCrbYeReVckdtq5DnvlhV+51rU+UNAD+wjr+1TrXzqRtUmzwQRTi35/LYmXKqSoDYc1ATSFkmWTNe9wsYF2exT5LMdM6ZhLIbp2dSFvlKQQels74XAVAOtz8F8HOqNaQHcVsU2oIlhWbWK75ZAEJwyuR5RQebRfg5Q2/H8UQYnwBqVBiij1EnT9EhvSdr5en3L8xChEeAqVMXmCAj+P93nypJjUwNAx20Po0v5EuCTMLxm3UPFfMB/U/UFVYDsLchGd2It5bH9E5H3+Bdso+AHdSHDwxgMyJEBF8d8bBzH3jBe6B3rrZnciNFI/n3dycUC8GvoCdhL1yOiGCoSHdymh42FpD3ZUr/6DGKYqNDQFCoQ9kG3iFh8Ap/aF8aAKo82uZ91C1rGK1rASNUsAQeYGm5sqhZlRNEcJ3BJre24ZoEIhAO1a5uuT5AnqOmwHCrZ8eM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
